[workspace]
members = ["assistants-core", "assistants-*"]
# Only check / build main crates by default (check all with `--workspace`)
default-members = ["assistants-core", "assistants-*"]
exclude = []
resolver = "2"
