services:
  - type: pserv
    name: assistants
    env: docker
    dockerCommand: "/bin/bash -c 'curl -L https://raw.githubusercontent.com/stellar-amenities/assistants/main/assistants-core/src/migrations.sql -o migrations.sql && psql -U postgres -d mydatabase -f migrations.sql && /app/entrypoint.sh'"
    image: 
      url: stellar-amenities/assistants/assistants:latest
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: pg
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: pserv
          property: connectionString
      - key: S3_ENDPOINT
        fromService:
          name: minio
          type: web
          property: host
      - key: S3_ACCESS_KEY
        fromService:
          name: minio
          type: web
          property: MINIO_ROOT_USER
      - key: S3_SECRET_KEY
        fromService:
          name: minio
          type: web
          property: MINIO_ROOT_PASSWORD
      - key: S3_BUCKET_NAME
        value: "mybucket"

  - type: redis
    name: lightning
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

  - type: web
    name: minio
    runtime: image
    healthCheckPath: /minio/health/live
    image:
      url: docker.io/minio/minio:RELEASE.2023-08-04T17-40-21Z.hotfix.04968f7ec
    dockerCommand: minio server /data
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
      - key: MINIO_ROOT_USER
        generateValue: true
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: MINIO_BROWSER
        value: "off"
databases:
  - name: pg
    plan: free
    databaseName: mydatabase
    user: valid_user_name
