# ! This does not run the Rust server (only db, queue, storage)
version: '3.8'
services:
  postgres:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    command: postgres
    # TODO
    # volumes:
    #   - ./pg-healthcheck.sh:/pg-healthcheck.sh
    # healthcheck:
    #   test: ["CMD-SHELL", "/healthcheck.sh"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 20s
  redis:
    container_name: redis 
    image: redis
    restart: always
    ports:
      - 6379:6379

  minio:
    container_name: minio1
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    command: ["serve", "phi"]
    profiles:
      - api

  assistants:
    container_name: assistants
    image: ghcr.io/stellar-amenities/assistants/assistants:latest
    platform: linux/arm64
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
      - minio
    profiles:
      - api
  