name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Start Docker containers
      run: docker-compose -f docker/docker-compose.yml up -d

    - name: Run tests
      env:
        ANTHROPIC_KEY: ${{ secrets.ANTHROPIC_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: RUST_TEST_THREADS=1 cargo test --features ci
